### ISSUE TITLE
Unable to export skinned animations from Mixamo

### ISSUE THREAD

**Issue by donmccurdy** [Kupoman/blendergltf#108]
I have a couple COLLADA models from Mixamo. All of them import correctly in Blender:

- [robot.zip](https://github.com/Kupoman/blendergltf/files/1423910/robot.zip) (mesh + t-pose)
- [robot@shoved.zip](https://github.com/Kupoman/blendergltf/files/1423911/robot.shoved.zip) (clip)
- [robot@stand.zip](https://github.com/Kupoman/blendergltf/files/1423912/robot.stand.zip) (clip)

![008c287a-e63e-433b-b2c6-0c028f5bdbd3-63478-00007b56dab119fe](https://user-images.githubusercontent.com/1848368/32131029-f719e926-bb58-11e7-93fd-d5b08ad9a431.gif)

My hope is to export all of them, either as separate glTF files or all merged together. When I try to export the t-pose, I get this error:

![screen shot 2017-10-27 at 8 50 59 pm](https://user-images.githubusercontent.com/1848368/32131020-dfe8193a-bb58-11e7-89ce-3bb15145dd40.png)

When trying to export one of the animation models, without any clips, there is a different error:

![screen shot 2017-10-27 at 8 31 43 pm](https://user-images.githubusercontent.com/1848368/32131026-ed65d7e6-bb58-11e7-983a-692eeed93f06.png)

Thanks!

**Comment by Kupoman** [comment]
I fixed the children key error, but I was unable to reproduce the first error. The first file, robot.zip, exported for me using default settings. Are you using the latest master, or at least the 1.1.1 release?

**Comment by donmccurdy** [comment]
Thanks! The animation is exporting without errors now.

I think what happened with `robot.zip` was that I'd clicked *Clear Animation Data* in Blender before exporting, hoping to get rid of the default pose. After doing that I can still reproduce the error on latest master, but it works as expected if I leave that animation alone, so for my purposes this is fine.

The animation merged in my scene is a bit ... unusual (see below) ... but I have no reason yet to think that is the exporters fault. Closing this bug out until I can look into it more. Thanks again. :)


![776ab695-c1b3-4f5a-9771-ced708db0e27-72520-000096df882347cc](https://user-images.githubusercontent.com/1848368/32140940-869b460e-bc2f-11e7-952a-a292ef748e77.gif)

**Comment by donmccurdy** [comment]
Quick update from the buggy screenshot above, for any future readers. I have this working as expected now. I was doing something wrong in the COLLADA import process from Mixamo to Blender, or its COLLADA exports were just incorrect to begin with. I followed the directions in [this video](https://www.youtube.com/watch?v=PHBWN2IIuck), using FBX, and used two suggestions from the video comments:

1. DON'T use the *Apply Transform* experimental option.
2. Select *Automatic Bone Orientation* during FBX import.

With that, I can export a glTF character containing multiple animations successfully:

![7bd62285-cc40-48b9-835c-1157d1816fdf-29773-00005c06aea11f5b](https://user-images.githubusercontent.com/1848368/32419297-8ee88468-c22c-11e7-97d0-40cca044412b.gif)
