### ISSUE TITLE
Animations do not export well if the mesh and armature have different origins

### ISSUE THREAD

**Issue by sctincman** [Kupoman/blendergltf#114]
A Blender project where I imported an OBJ+MTL file, rigged the model, and animated it, fails to texture when loaded in three.js. Additionally the animation has vertex errors when played. When exported using the Khronos exporter, the model textures, and the animation has no noticeable errors.

The raw blender project is located here https://github.com/sctincman/gameoff2017/blob/master/src/blender/fox.blend, the original OBJ mesh used was taken from [here](https://poly.google.com/view/10u8FYPC5Br), and imported into blender.

A modified three.js example is attached (exported model expected at "models/gltf/fox/" relative to html file.

[demo.zip](https://github.com/Kupoman/blendergltf/files/1493755/demo.zip)

Additionally, the GLTF export appears to have extra nodes. There are 3 copies of the Fox node "Fox, Fox.001, Fox.002", and the top-level scene contains an extra "Root" scene node below it.
```
+ Scene
|-- + Scene_Root
    | -- Fox
    | -- Camera
    | -- Sun
```

[fox.gltf.zip](https://github.com/Kupoman/blendergltf/files/1494534/fox.gltf.zip)

Kupoman exported
![screenshot from 2017-11-21 20-21-59](https://user-images.githubusercontent.com/87428/33108496-ae621df2-cef9-11e7-824a-290e5ad503b8.png)

Khronos exported
![screenshot from 2017-11-21 20-19-02](https://user-images.githubusercontent.com/87428/33108761-1437499e-cefb-11e7-8268-5958a6908311.png)

**Comment by sctincman** [comment]
Some updates. The texture issue appears to be a regression from 1.1.1. Checking out that tag fixed the texture issue for me.

I found a workaround for the animation errors. They were fixed by clearing the positions/origins of my mesh and skeleton, then repositioning the skeleton. I had seen this as a workaround for the three.js exporter somewhere else, and it appears to work here. No information from that other source about why the exporter can be fixed by this.

**Comment by Kupoman** [comment]
@sctincman, the .blend file you linked me to does not appear to include texture(s). Could you either pack the texture(s) into the .blend file, or include them with the .blend file in a .zip? Also, what commit of master where you using before going back to 1.1.1? There were some texture regressions introduced 6266f607ee9a578e7a07f835227bec6c1a3f1755 that should have been fixed by 6342410e3eacf76b02796f323e2045516efbf5c6.

**Comment by Kupoman** [comment]
There is definitely a bug with the animations. I noticed that the skull bone on the Idle animation does not have a translation channel. Adding translation to the animation also fixes the problem.

There also appears to be a problem with exporting the texture coordinates. The accessor and bufffer view for the texture coordinate data appear to be in disagreement on some lengths.

**Comment by tkazik** [comment]
I am also having troubles with a textured model. It works nice in blender, but I am having issues with both gltf exporters. If you want to have a look at the model, I would greatly appreciate it (the b737 model at the bottom of the conversation):
 
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/115#event-1348353227

Thx!

**Comment by Kupoman** [comment]
@tkazik The zip file does not appear to include the textures, and they are not packed into the blend file. Could you please repackage the sample with the textures, I would love to take a look at it.

**Comment by tkazik** [comment]
I am sorry...this one includes the texture.

[b737.zip](https://github.com/Kupoman/blendergltf/files/1497567/b737.zip)

**Comment by Kupoman** [comment]
It looks like bf0d4af55926f46ca132b5c21ca08567c3dcbd99 broke some mesh processing, and is causing the exporter to crash when trying to export the b737 file. I would recommend reverting that commit, using a commit before it, or using 1.1.1 while I continue investigating these new problems.

**Comment by sctincman** [comment]
@Kupoman I think I was using 6266f60. I updated to the newest commit and it is texturing, but appears to be using incorrect UVs.

> the .blend file you linked me to does not appear to include texture(s)

Ah, my apologies, this blend should have the image packed in it.
[fox.blend.zip](https://github.com/Kupoman/blendergltf/files/1497790/fox.blend.zip)

**Comment by Kupoman** [comment]
Looks like UVs for non-interleaved mesh data have been broken for a while. I recently changed the default of the "Interleave Vertex Data" setting to disabled. If your importing application can handle it, you can enable that option as a work-around.

**Comment by Kupoman** [comment]
I have pushed a few commits to fix up some problems, including fixing UVs when not interleaving vertex data.

@sctincman The extra root node is to convert from Z-up to Y-up. I think the other extra nodes you mentioned were fixed by aea827158b178fbd628b8a0556954ac68f106b1c, because I am not seeing them with the latest master.

I think that leaves 2 bugs that have been brought up in this issue. There is the problem with translated armatures, and the landing gear flap on that 737 being in the wrong spot. I am still investigating ways to fix the translated armature problem. The second problem is due to poor bone parent support. We can start tracking bone parenting issues in #115.

**Comment by sctincman** [comment]
@Kupoman I think I attempted interleaved export previously, but it was broken at the time. Interleaving vertex data now textures properly for me. Thanks!

However, as of da52ba085f1ddb11243dce45a9542948f2aa2ab4 I am getting an error on export without interleaving

```
Traceback (most recent call last):
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/__init__.py", line 467, in execute
    gltf = export_gltf(data, settings)
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/blendergltf.py", line 1790, in export_gltf
    ] for exporter in exporters
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/blendergltf.py", line 1790, in <dictcomp>
    ] for exporter in exporters
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/blendergltf.py", line 1789, in <listcomp>
    for data in state['input'].get(exporter.blender_key, [])
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/blendergltf.py", line 786, in export_mesh
    buf, gltf_attrs = export_attributes(state, mesh, vert_list, None)
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/blendergltf.py", line 670, in export_attributes
    cdata[j][i * 3] = col[0]
  File "/home/tincman/.config/blender/2.79/scripts/addons/blendergltf/blendergltf.py", line 272, in __setitem__
    struct.pack_into(self._ctype, self._buffer_data, ptr, value)
struct.error: pack_into requires a buffer of at least 4 bytes

location: <unknown location>:-1
```


> The extra root node is to convert from Z-up to Y-up 

Ah ha, that makes sense now that I look at it, thanks again.

**Comment by Kupoman** [comment]
@sctincman Would you mind filing a new bug for that packing issue with the blend file and settings you used?

**Comment by Kupoman** [comment]
@sctincman Actually, I found the problem with non-interleaved meshes. Should be fixed by 086e3a907f7194fb641d0640fc3ba5a5e6a05e7b.

**Comment by Kupoman** [comment]
Updating the title to better match the current state of this issue.

**Comment by Kupoman** [comment]
I think I finally found the problem. I have submitted a fix and the fox file appears to be working now. If there are still some files that do not work when the mesh and armature have different origins, we can reopen this issue. Otherwise, further problems should get their own issue.

**Comment by tkazik** [comment]
Good news! I just updated and tested the B737 animation.
Unfortunately, I still get errors...do you mind taking a look?
(files are above...thx!)

**Comment by Kupoman** [comment]
@tkazik Thanks for testing it. I'll take a look at it.

**Comment by Kupoman** [comment]
@tkazik The errors were unrelated to this bug, but they should be fixed now.
